### ISSUE TITLE
キャンプの時に手軽に作れる最高に旨いレシピを考案する

### ISSUE THREAD

**Issue by a2chub** [sinmetal/slide#13]
制限は以下のとおり
材料費は1名： 3000円未満。
コンロは3つ

**Comment by sinmetal** [comment]
@a2chub BBQやるか、 http://cookpad.com/search/%E3%83%81%E3%83%AA%E3%83%93%E3%83%BC%E3%83%B3%E3%82%BA でも作ってください！
