### ISSUE TITLE
esa.ioを社内導入すると嬉しくなるかどうか調査

### ISSUE THREAD

**Issue by grapswiz** [sinmetal/slide#14]
これ: https://esa.io/

見た目こんな感じらしい: https://docs.esa.io/

**Comment by vvakame** [comment]
https://twitter.com/vvakame/statuses/591081127328133120

**Comment by a2chub** [comment]
なんとなくコレ使ってるけど、そこそこ使いやすいぉ
https://docbase.io/

esa.ioもよさげですな
