### ISSUE TITLE
Sinmetal Craft Server 整備

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/slide#15]
だれでもMinecraft ServerのRestartができるように設定する

**Comment by pyrovers** [comment]
プレイヤー情報とかとれるっぽい
http://roamer7038.hatenablog.com/entry/2014/02/23/223357

**Comment by sinmetal** [comment]
@pyrovers すばらしい知見である。これは試してみたいね

**Comment by sinmetal** [comment]
minecraftのログをSlackにぶっこんだり、だれでもサーバできるようにした。

https://github.com/sinmetal/sinmetalcraft
